// client/src/views/admin/ChatbotConfig.vue
<template>
  <div class="chatbot-config">
    <h1>Chatbot Configuration</h1>
    
    <div class="config-form" v-if="config">
      <div class="form-group">
        <label>Welcome Message</label>
        <textarea 
          v-model="config.welcomeMessage"
          rows="3"
          placeholder="Enter welcome message..."
        ></textarea>
      </div>

      <div class="form-group">
        <label>Primary Color</label>
        <input 
          type="color" 
          v-model="config.primaryColor"
        >
      </div>

      <div class="form-group">
        <label>Secondary Color</label>
        <input 
          type="color" 
          v-model="config.secondaryColor"
        >
      </div>

      <div class="form-group">
        <label>Width (px)</label>
        <input 
          type="number" 
          v-model="config.width"
          min="200"
          max="800"
        >
      </div>

      <div class="form-group">
        <label>Height (px)</label>
        <input 
          type="number" 
          v-model="config.height"
          min="300"
          max="800"
        >
      </div>

      <div class="form-group">
        <label>Position</label>
        <select v-model="config.position">
          <option value="bottom-right">Bottom Right</option>
          <option value="bottom-left">Bottom Left</option>
          <option value="top-right">Top Right</option>
          <option value="top-left">Top Left</option>
        </select>
      </div>

      <div class="form-actions">
        <button class="btn-save" @click="saveConfig">
          Save Changes
        </button>
        <button class="btn-preview" @click="previewConfig">
          Preview
        </button>
      </div>
    </div>

    <div v-else class="loading">
      Loading configuration...
    </div>

    <!-- Preview Modal -->
    <div class="preview-modal" v-if="showPreview">
      <div class="preview-content">
        <div class="preview-header">
          <h3>Chatbot Preview</h3>
          <button class="close-btn" @click="showPreview = false">
            <i class="fas fa-times"></i>
          </button>
        </div>
        <div class="preview-body">
          <Chatbot :config="config" />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, onMounted } from 'vue'
import axios from 'axios'
import Chatbot from '@/components/Chatbot.vue'

export default {
  name: 'ChatbotConfig',
  components: {
    Chatbot
  },
  setup() {
    const config = ref(null)
    const showPreview = ref(false)

    const fetchConfig = async () => {
      try {
        const response = await axios.get('/api/chatbot/config')
        config.value = response.data
      } catch (error) {
        console.error('Error fetching config:', error)
      }
    }

    const saveConfig = async () => {
      try {
        await axios.put('/api/chatbot/config', config.value)
        alert('Configuration saved successfully!')
      } catch (error) {
        console.error('Error saving config:', error)
        alert('Failed to save configuration')
      }
    }

    const previewConfig = () => {
      showPreview.value = true
    }

    onMounted(fetchConfig)

    return {
      config,
      showPreview,
      saveConfig,
      previewConfig
    }
  }
}
</script>

<style scoped>
.chatbot-config {
  max-width: 800px;
  margin: 0 auto;
}

h1 {
  margin-bottom: 2rem;
  color: #2c3e50;
}

.config-form {
  background: white;
  padding: 2rem;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.form-group {
  margin-bottom: 1.5rem;
}

label {
  display: block;
  margin-bottom: 0.5rem;
  color: #2c3e50;
  font-weight: 500;
}

input[type="text"],
input[type="number"],
textarea,
select {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 1rem;
}

input[type="color"] {
  width: 100px;
  height: 40px;
  padding: 2px;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.form-actions {
  display: flex;
  gap: 1rem;
  margin-top: 2rem;
}

button {
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 4px;
  font-size: 1rem;
  cursor: pointer;
  transition: all 0.3s ease;
}

.btn-save {
  background: #3498db;
  color: white;
}

.btn-save:hover {
  background: #2980b9;
}

.btn-preview {
  background: #2ecc71;
  color: white;
}

.btn-preview:hover {
  background: #27ae60;
}

.loading {
  text-align: center;
  padding: 2rem;
  color: #666;
}

.preview-modal {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0,0,0,0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.preview-content {
  background: white;
  width: 90%;
  max-width: 1000px;
  height: 80vh;
  border-radius: 8px;
  overflow: hidden;
}

.preview-header {
  padding: 1rem;
  border-bottom: 1px solid #ddd;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.preview-header h3 {
  margin: 0;
  color: #2c3e50;
}

.close-btn {
  background: none;
  border: none;
  font-size: 1.25rem;
  cursor: pointer;
  color: #666;
}

.preview-body {
  height: calc(100% - 60px);
  padding: 1rem;
  overflow: auto;
}
</style>

// client/src/pages/admin/chatbot/ChatbotConfig.jsx
import React, { useState, useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { toast } from 'react-toastify';
import axios from 'axios';

const ChatbotConfig = () => {
    const [config, setConfig] = useState({
        welcomeMessage: '',
        theme: {
            primaryColor: '#4a90e2',
            secondaryColor: '#357abd',
            backgroundColor: '#ffffff',
            textColor: '#2c3e50'
        },
        avatar: '🤖',
        title: '',
        position: {
            bottom: 20,
            right: 20
        },
        size: {
            width: 380,
            height: 600
        },
        isActive: true
    });

    const [loading, setLoading] = useState(false);

    useEffect(() => {
        fetchConfig();
    }, []);

    const fetchConfig = async () => {
        try {
            const response = await axios.get('/api/chatbot');
            setConfig(response.data);
        } catch (error) {
            console.error('Error fetching config:', error);
            toast.error('Không thể tải cấu hình chatbot');
        }
    };

    const handleChange = (e) => {
        const { name, value } = e.target;
        if (name.includes('.')) {
            const [parent, child] = name.split('.');
            setConfig(prev => ({
                ...prev,
                [parent]: {
                    ...prev[parent],
                    [child]: value
                }
            }));
        } else {
            setConfig(prev => ({
                ...prev,
                [name]: value
            }));
        }
    };

    const handleNumberChange = (e) => {
        const { name, value } = e.target;
        const [parent, child] = name.split('.');
        setConfig(prev => ({
            ...prev,
            [parent]: {
                ...prev[parent],
                [child]: parseInt(value) || 0
            }
        }));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);
        try {
            await axios.put('/api/chatbot', config);
            toast.success('Cập nhật cấu hình thành công');
        } catch (error) {
            console.error('Error updating config:', error);
            toast.error('Không thể cập nhật cấu hình');
        }
        setLoading(false);
    };

    const handleToggle = async () => {
        try {
            const response = await axios.put('/api/chatbot/toggle');
            setConfig(prev => ({
                ...prev,
                isActive: response.data.isActive
            }));
            toast.success(`Chatbot đã được ${response.data.isActive ? 'bật' : 'tắt'}`);
        } catch (error) {
            console.error('Error toggling chatbot:', error);
            toast.error('Không thể thay đổi trạng thái chatbot');
        }
    };

    return (
        <div className="p-4">
            <div className="flex justify-between items-center mb-6">
                <h1 className="text-2xl font-bold">Cấu hình Chatbot</h1>
                <button
                    onClick={handleToggle}
                    className={`px-4 py-2 rounded ${
                        config.isActive
                            ? 'bg-red-500 hover:bg-red-600'
                            : 'bg-green-500 hover:bg-green-600'
                    } text-white`}
                >
                    {config.isActive ? 'Tắt Chatbot' : 'Bật Chatbot'}
                </button>
            </div>

            <form onSubmit={handleSubmit} className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* Thông tin cơ bản */}
                    <div className="space-y-4">
                        <h2 className="text-xl font-semibold">Thông tin cơ bản</h2>
                        
                        <div>
                            <label className="block text-sm font-medium mb-1">
                                Tin nhắn chào mừng
                            </label>
                            <textarea
                                name="welcomeMessage"
                                value={config.welcomeMessage}
                                onChange={handleChange}
                                className="w-full p-2 border rounded"
                                rows="3"
                            />
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-1">
                                Avatar
                            </label>
                            <input
                                type="text"
                                name="avatar"
                                value={config.avatar}
                                onChange={handleChange}
                                className="w-full p-2 border rounded"
                            />
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-1">
                                Tiêu đề
                            </label>
                            <input
                                type="text"
                                name="title"
                                value={config.title}
                                onChange={handleChange}
                                className="w-full p-2 border rounded"
                            />
                        </div>
                    </div>

                    {/* Màu sắc */}
                    <div className="space-y-4">
                        <h2 className="text-xl font-semibold">Màu sắc</h2>
                        
                        <div>
                            <label className="block text-sm font-medium mb-1">
                                Màu chính
                            </label>
                            <div className="flex items-center gap-2">
                                <input
                                    type="color"
                                    name="theme.primaryColor"
                                    value={config.theme.primaryColor}
                                    onChange={handleChange}
                                    className="w-12 h-12 p-1 border rounded"
                                />
                                <input
                                    type="text"
                                    name="theme.primaryColor"
                                    value={config.theme.primaryColor}
                                    onChange={handleChange}
                                    className="flex-1 p-2 border rounded"
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-1">
                                Màu phụ
                            </label>
                            <div className="flex items-center gap-2">
                                <input
                                    type="color"
                                    name="theme.secondaryColor"
                                    value={config.theme.secondaryColor}
                                    onChange={handleChange}
                                    className="w-12 h-12 p-1 border rounded"
                                />
                                <input
                                    type="text"
                                    name="theme.secondaryColor"
                                    value={config.theme.secondaryColor}
                                    onChange={handleChange}
                                    className="flex-1 p-2 border rounded"
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-1">
                                Màu nền
                            </label>
                            <div className="flex items-center gap-2">
                                <input
                                    type="color"
                                    name="theme.backgroundColor"
                                    value={config.theme.backgroundColor}
                                    onChange={handleChange}
                                    className="w-12 h-12 p-1 border rounded"
                                />
                                <input
                                    type="text"
                                    name="theme.backgroundColor"
                                    value={config.theme.backgroundColor}
                                    onChange={handleChange}
                                    className="flex-1 p-2 border rounded"
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-1">
                                Màu chữ
                            </label>
                            <div className="flex items-center gap-2">
                                <input
                                    type="color"
                                    name="theme.textColor"
                                    value={config.theme.textColor}
                                    onChange={handleChange}
                                    className="w-12 h-12 p-1 border rounded"
                                />
                                <input
                                    type="text"
                                    name="theme.textColor"
                                    value={config.theme.textColor}
                                    onChange={handleChange}
                                    className="flex-1 p-2 border rounded"
                                />
                            </div>
                        </div>
                    </div>

                    {/* Vị trí và kích thước */}
                    <div className="space-y-4">
                        <h2 className="text-xl font-semibold">Vị trí</h2>
                        
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-medium mb-1">
                                    Khoảng cách dưới (px)
                                </label>
                                <input
                                    type="number"
                                    name="position.bottom"
                                    value={config.position.bottom}
                                    onChange={handleNumberChange}
                                    className="w-full p-2 border rounded"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium mb-1">
                                    Khoảng cách phải (px)
                                </label>
                                <input
                                    type="number"
                                    name="position.right"
                                    value={config.position.right}
                                    onChange={handleNumberChange}
                                    className="w-full p-2 border rounded"
                                />
                            </div>
                        </div>
                    </div>

                    <div className="space-y-4">
                        <h2 className="text-xl font-semibold">Kích thước</h2>
                        
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-medium mb-1">
                                    Chiều rộng (px)
                                </label>
                                <input
                                    type="number"
                                    name="size.width"
                                    value={config.size.width}
                                    onChange={handleNumberChange}
                                    className="w-full p-2 border rounded"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium mb-1">
                                    Chiều cao (px)
                                </label>
                                <input
                                    type="number"
                                    name="size.height"
                                    value={config.size.height}
                                    onChange={handleNumberChange}
                                    className="w-full p-2 border rounded"
                                />
                            </div>
                        </div>
                    </div>
                </div>

                <div className="flex justify-end">
                    <button
                        type="submit"
                        disabled={loading}
                        className="px-6 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 disabled:opacity-50"
                    >
                        {loading ? 'Đang lưu...' : 'Lưu cấu hình'}
                    </button>
                </div>
            </form>
        </div>
    );
};

export default ChatbotConfig;
